'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { toast } from 'react-hot-toast'

interface Triple {
    id: string
    subject: { label: string }
    predicate: { label: string }
    object: { label: string }
    trustSignal: number
    attestersCount: number
    provenance: { account: string; label?: string; shares: number }[]
}

interface UseAISummaryOptions {
    atomLabel: string
    atomId: string
    triples: Triple[]
    isLoading: boolean
    autoGenerate?: boolean
}

interface UseAISummaryReturn {
    summary: string
    isGenerating: boolean
    isCopied: boolean
    hasGenerated: boolean
    generate: () => void
    copyToClipboard: () => Promise<void>
}

function formatSummary(atomLabel: string, atomId: string, triples: Triple[]): string {
    if (triples.length === 0) return ''

    const header = `Verified facts about "${atomLabel}" (Atom ID: ${atomId}):`
    const separator = '─'.repeat(50)

    const entries = triples.slice(0, 10).map((t, i) => {
        const trustStr = `${t.trustSignal.toFixed(4)} $TRUST`
        const endorseStr = t.attestersCount > 0
            ? `endorsed by ${t.attestersCount} address${t.attestersCount !== 1 ? 'es' : ''}`
            : 'unendorsed'

        let entry = `${i + 1}. ${t.predicate.label || 'relates to'} → ${t.object.label || 'unknown'}`
        entry += `\n   Trust: ${trustStr} (${endorseStr})`

        if (t.provenance.length > 0) {
            const topAttester = t.provenance[0]
            const attesterLabel = topAttester.label
                || `${topAttester.account.slice(0, 6)}…${topAttester.account.slice(-4)}`
            entry += `\n   Provenance: Attested by ${attesterLabel} via Intuition Protocol`
        }

        return entry
    })

    const footer = [
        '',
        separator,
        `Source: TrustGraph / Intuition Protocol (Testnet Beta)`,
        `Generated: ${new Date().toISOString().split('T')[0]}`,
        `Total claims: ${triples.length} | Showing top ${Math.min(triples.length, 10)}`,
    ].join('\n')

    return [header, separator, ...entries, footer].join('\n')
}

export function useAISummary({
    atomLabel,
    atomId,
    triples,
    isLoading,
    autoGenerate = true,
}: UseAISummaryOptions): UseAISummaryReturn {
    const [summary, setSummary] = useState('')
    const [isGenerating, setIsGenerating] = useState(false)
    const [isCopied, setIsCopied] = useState(false)
    const [hasGenerated, setHasGenerated] = useState(false)
    const autoGeneratedRef = useRef(false)

    const generate = useCallback(() => {
        if (triples.length === 0) return

        setIsGenerating(true)
        setSummary('')

        // Simulate processing delay for UX polish
        const delay = 800 + Math.random() * 600
        setTimeout(() => {
            const text = formatSummary(atomLabel, atomId, triples)
            setSummary(text)
            setIsGenerating(false)
            setHasGenerated(true)
            toast.success('Verifiable summary generated!', { icon: '✨' })
        }, delay)
    }, [atomLabel, atomId, triples])

    // Auto-generate on mount when data becomes available
    useEffect(() => {
        if (
            autoGenerate &&
            !isLoading &&
            triples.length > 0 &&
            !hasGenerated &&
            !isGenerating &&
            !autoGeneratedRef.current
        ) {
            autoGeneratedRef.current = true
            generate()
        }
    }, [autoGenerate, isLoading, triples, hasGenerated, isGenerating, generate])

    const copyToClipboard = useCallback(async () => {
        if (!summary) return

        try {
            await navigator.clipboard.writeText(summary)
            setIsCopied(true)
            toast.success('Summary copied — paste into any AI chat!', { icon: '📋' })
            setTimeout(() => setIsCopied(false), 2500)
        } catch {
            // Fallback for older browsers
            const textarea = document.createElement('textarea')
            textarea.value = summary
            document.body.appendChild(textarea)
            textarea.select()
            document.execCommand('copy')
            document.body.removeChild(textarea)
            setIsCopied(true)
            toast.success('Summary copied!', { icon: '📋' })
            setTimeout(() => setIsCopied(false), 2500)
        }
    }, [summary])

    return {
        summary,
        isGenerating,
        isCopied,
        hasGenerated,
        generate,
        copyToClipboard,
    }
}
